name: preview

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: write

jobs:
  deploy-preview:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Build MkDocs website
        run: |
          pip install -r docs/requirements.txt
          mkdocs build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./site
          publish_branch: preview-${{ github.event.pull_request.number }}

      - name: Comment PR
        uses: actions/github-script@v3
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const issue_number = context.issue.number;
            const repo = context.repo;
            const url = `https://${repo.owner}.github.io/${repo.repo}/preview-${issue_number}`;
            github.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: `Preview URL: ${url}`
            });




      - name: Install Netlify CLI
        run: npm install -g netlify-cli

      # Don't expose secrets to any other process other than the `netlify` cli;
      # don't risk rogue dependencies pulling our secrets
      - name: Deploy Preview to Netlify
        run: |
          netlify deploy \
            --dir="site" \
            --alias="${GITHUB_REPOSITORY#*/}-${{ github.event.number }}"
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_PREVIEW_APP_SITE_ID }}

      - name: Add Netlify link PR comment
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const hostnameSuffix = "cal-itp-previews.netlify.app"
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `Preview url: https://${context.repo.repo}-${{ github.event.number }}--${hostnameSuffix}`,
            })
