name: PR Preview

on:
  pull_request_target:
    types: [opened, reopened, synchronize]

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ## Deploying with :page_facing_up: GitHub Pages

            | **Commit:** | ${{ github.event.pull_request.head.sha }} |
            | :-- | :-- |
            | **Status:** | 🔨 Building |
            | **Deploy Log:** | ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }} |
